### ISSUE TITLE
Objects in a Task need to know who contains it

### ISSUE THREAD

**Issue by atygesen** [muhrin/minkipy#5]
Going from a minki Task and finding the objects within it is easy enough, but going the other way in the tree is difficult.

I suggest when we place an object in a task, we have a tag in that object, so the minki Task tells that object "I'm working on you". Challenge with this: How do we propagate that down to objects inside those, e.g. a flow I have right now

`minki.Task` -> `Workflow` -> `VaspTask` -> `VaspRun` 

It would be neat if such tags could propagate all the way down, so if I'm sitting in the `VaspRun` I'd know exactly which task has done work on me (bonus: Could it also be able to know which Workflow object has run on it?)

**Comment by muhrin** [comment]
This is now possible with mincepy's `historian.references.get_obj_ref_graph`.
