### ISSUE TITLE
minki list enhancement: show totals and other summary

### ISSUE THREAD

**Issue by atygesen** [muhrin/minkipy#6]
It would be nice to have a summary function for what's in the list

At minimum, just show the total number in the queue

If we allow for knowing more about what's in pyos, then it would be nice to also have like

```
Tasks in /maibat/fcc/full: <some count>
Tasks in /maibat/bcc/full: <some count>
Tasks in total: <total>
```

**Comment by muhrin** [comment]
This has now been implemented in20f30222db17f680087fd07dcd0e9b0dc6257446.  Shows totals as part of the summary if the `-c` flag is used.  If `pyos` is installed will also show task counts on a per-folder basis.
